### ISSUE TITLE
(No output on stdout) stderr: 

### ISSUE THREAD

**Issue by msrajanadar** [NagiosEnterprises/nrdp#47]
I am getting the below error and the status is showing Ok and is green
(No output on stdout) stderr:
<img width="983" alt="nagios_error" src="https://user-images.githubusercontent.com/8028491/70028484-cae7fe00-15ca-11ea-8daa-b16ba193a8e9.png">
I am using Nagios Core Version 4.4.4

**Comment by ericloyd** [comment]
Looks like your plugin (which I'm guessing is check_by_ssh) is not working correctly, but returning an OK to Nagios.  In other words, the SSH connection is working, but the plugin that is being executed is not working.

Having said that, now I'm not so sure because the Port 22 check might check from the outside to see if port 22 is listening.  There simply isn't enough information.

You might have better luck asking this on the Nagios Core support forum at https://support.nagios.com/forum/viewforum.php?f=7, since many more people will read it there.  I would ask to see the configuration for the SSH Port 22 check and the Check Load check as examples, and from that, I could make a better recommendation.

**Comment by msrajanadar** [comment]
Thanks a lot for your response, am using passive check to upload all the plugin output to nagios server as the client host can not be reached directly
for some reason the cron failed to upload the plugin output and i did not get any alert; just got to know after almost 99days; not sure what when wrong

**Comment by ericloyd** [comment]
Ah.  Okay, I see that now.  Here's what happens with a passive check - if there is no update to the passive check, then the check stays in whatever the last state was.  Looks like you need to fix your NRDP to actually send proper data and check the token.  You will also want to read about Passive Checks (https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/passivechecks.html) and look at freshness checking.  This way, you can flag things that haven't been updated after an expected amount of time.

**Comment by msrajanadar** [comment]
Thanks a lot, the issue was long resolved by upgrading nagios and adding an dummy active check which will fail. if the passive check fails then nagios forces the passive check to active and follows the same flow as that of an active check
